# Generated by Django 4.2.16 on 2025-01-18 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_alter_timetableentry_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marklisttable',
            old_name='regno',
            new_name='mark',
        ),
        migrations.RemoveField(
            model_name='marklisttable',
            name='address',
        ),
        migrations.RemoveField(
            model_name='marklisttable',
            name='department',
        ),
        migrations.RemoveField(
            model_name='marklisttable',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='marklisttable',
            name='phoneno',
        ),
        migrations.RemoveField(
            model_name='marklisttable',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='marklisttable',
            name='studentname',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='department',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='hour',
        ),
        migrations.AddField(
            model_name='marklisttable',
            name='studentid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administrator.studenttable'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='CLASS',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.class'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='slot_10_11',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='slot_10_11', to='administrator.subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='slot_11_12',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='slot_11_12', to='administrator.subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='slot_1_2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='slot_1_2', to='administrator.subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='slot_2_3',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='slot_2_3', to='administrator.subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='slot_3_4',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='slot_3_4', to='administrator.subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='slot_9_10',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='slot_9_10', to='administrator.subject'),
            preserve_default=False,
        ),
    ]
