# Generated by Django 4.2.16 on 2025-01-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_rename_regno_marklisttable_mark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markuptable',
            name='mark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
