# Generated by Django 4.2.16 on 2025-01-18 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_alter_markuptable_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='taskTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(blank=True, max_length=100, null=True)),
                ('facultyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.facultytable')),
            ],
        ),
    ]
