# Generated by Django 4.2.16 on 2025-01-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_tasktable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complainttable',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
