# Generated by Django 4.2.16 on 2025-01-25 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_alter_complainttable_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenttable',
            name='regno',
        ),
    ]
