# Generated by Django 4.2.16 on 2025-01-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0008_remove_studenttable_regno'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttable',
            name='email',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
