# Generated by Django 4.2.16 on 2025-01-25 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0009_studenttable_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studenttable',
            old_name='LOGIN',
            new_name='LOGINID',
        ),
    ]
