# Generated by Django 4.2.16 on 2025-01-25 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0010_rename_login_studenttable_loginid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttable',
            name='LOGINID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.logintable'),
        ),
    ]
