# Generated by Django 4.2.18 on 2025-02-02 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0011_alter_studenttable_loginid'),
    ]

    operations = [
        migrations.CreateModel(
            name='answerTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answer', models.CharField(blank=True, max_length=500, null=True)),
                ('taskid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.tasktable')),
            ],
        ),
    ]
