# Generated by Django 5.1.4 on 2025-02-08 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0012_answertable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='answerTable',
        ),
    ]
