# Generated by Django 5.1.4 on 2025-02-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0014_studenttable_regno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttable',
            name='regno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
