# Generated by Django 5.1.4 on 2025-02-08 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0015_alter_studenttable_regno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markuptable',
            name='STUDENT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='administrator.studenttable'),
        ),
    ]
