# Generated by Django 5.1.4 on 2025-02-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0016_alter_markuptable_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
