# Generated by Django 5.1.4 on 2025-02-08 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0017_uploadedcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedcode',
            name='output',
            field=models.FileField(blank=True, null=True, upload_to='output/'),
        ),
    ]
