# Generated by Django 5.1.4 on 2025-02-08 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0018_uploadedcode_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedcode',
            name='taskid',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='administrator.tasktable'),
            preserve_default=False,
        ),
    ]
