# Generated by Django 5.1.6 on 2025-03-03 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0019_uploadedcode_taskid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktable',
            name='taskcode',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasktable',
            name='taskcodestatus',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedcode',
            name='taskid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.tasktable'),
        ),
    ]
