# Generated by Django 5.1.6 on 2025-03-03 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0020_tasktable_taskcode_tasktable_taskcodestatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktable',
            name='taskcodestatus',
            field=models.CharField(blank=True, default='accept', max_length=100, null=True),
        ),
    ]
